### ISSUE TITLE
Unable to start app

### ISSUE THREAD

**Issue by pts-teddyhwang** [isliliye/beers#1]
I'm getting the following error:
```
teddy.hwang@pts-thwang:~/Sites/Points/hr-assignments/lili-ye (lili-ye*)$ ./node_modules/.bin/webpack-dev-server .
/Users/teddy.hwang/Sites/Points/hr-assignments/lili-ye/node_modules/webpack-dev-server/bin/webpack-dev-server.js:386
                throw e;
                ^

Error: `output.path` needs to be an absolute path or `/`.
    at Object.setFs (/Users/teddy.hwang/Sites/Points/hr-assignments/lili-ye/node_modules/webpack-dev-middleware/lib/Shared.js:88:11)
    at Shared (/Users/teddy.hwang/Sites/Points/hr-assignments/lili-ye/node_modules/webpack-dev-middleware/lib/Shared.js:214:8)
    at module.exports (/Users/teddy.hwang/Sites/Points/hr-assignments/lili-ye/node_modules/webpack-dev-middleware/middleware.js:22:15)
    at new Server (/Users/teddy.hwang/Sites/Points/hr-assignments/lili-ye/node_modules/webpack-dev-server/lib/Server.js:56:20)
    at startDevServer (/Users/teddy.hwang/Sites/Points/hr-assignments/lili-ye/node_modules/webpack-dev-server/bin/webpack-dev-server.js:379:12)
    at /Users/teddy.hwang/Sites/Points/hr-assignments/lili-ye/node_modules/webpack-dev-server/bin/webpack-dev-server.js:325:3
    at /Users/teddy.hwang/Sites/Points/hr-assignments/lili-ye/node_modules/portfinder/lib/portfinder.js:160:14
    at /Users/teddy.hwang/Sites/Points/hr-assignments/lili-ye/node_modules/portfinder/node_modules/async/lib/async.js:52:16
    at /Users/teddy.hwang/Sites/Points/hr-assignments/lili-ye/node_modules/portfinder/node_modules/async/lib/async.js:269:32
    at /Users/teddy.hwang/Sites/Points/hr-assignments/lili-ye/node_modules/portfinder/node_modules/async/lib/async.js:44:16
```

I tried updating `webpack.config.js` and modifying `output.path` to be `process.cwd() + "/dist"`. But then got the following error:

```teddy.hwang@pts-thwang:~/Sites/Points/hr-assignments/lili-ye (lili-ye*)$ ./node_modules/.bin/webpack-dev-server
Project is running at http://localhost:8080/
webpack output is served from /
Hash: 4908d360d31c2fc25047
Version: webpack 2.2.1
Time: 6010ms
    Asset     Size  Chunks                    Chunk Names
bundle.js  1.06 MB       0  [emitted]  [big]  main
chunk    {0} bundle.js (main) 1.03 MB [entry] [rendered]
   [26] ./~/react/lib/React.js 2.69 kB {0} [built]
   [66] ./~/react/react.js 56 bytes {0} [built]
  [114] ./entry.js 6.55 kB {0} [built]
  [115] (webpack)-dev-server/client?http://localhost:8080 4.9 kB {0} [built]
  [118] ./components/header.js 2.97 kB {0} [built]
  [119] ./components/list_items.js 5.04 kB {0} [built]
  [139] ./~/isomorphic-fetch/fetch-npm-browserify.js 233 bytes {0} [built]
  [141] ./~/punycode/punycode.js 14.7 kB {0} [built]
  [146] ./~/react-dom/index.js 59 bytes {0} [built]
  [256] ./~/strip-ansi/index.js 161 bytes {0} [built]
  [258] ./~/url/url.js 23.3 kB {0} [built]
  [260] (webpack)-dev-server/client/overlay.js 3.59 kB {0} [built]
  [261] (webpack)-dev-server/client/socket.js 856 bytes {0} [built]
  [263] (webpack)/hot/emitter.js 77 bytes {0} [built]
  [265] multi (webpack)-dev-server/client?http://localhost:8080 ./entry.js 40 bytes {0} [built]
     + 251 hidden modules

ERROR in ./components/list_items.js
Module not found: Error: Can't resolve 'css' in '/Users/teddy.hwang/Sites/Points/hr-assignments/lili-ye'
 @ ./components/list_items.js 13:0-23
 @ ./entry.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./entry.js
webpack: Failed to compile.
```

I noticed the requirement was for webpack 1.x so tried downgrading `webpack-dev-server` to 1.x branch and got a different error:

```
ERROR in ./components/list_items.js
Module not found: Error: Cannot resolve module 'style' in /Users/teddy.hwang/Sites/Points/hr-assignments/lili-ye/components
 @ ./components/list_items.js 13:0-23
webpack: Failed to compile.
```

**Comment by pts-teddyhwang** [comment]
Okay, figured it out with the following changes:
```
diff --git a/lili-ye/package.json b/lili-ye/package.json
index f1d205b..30f716c 100644
--- a/lili-ye/package.json
+++ b/lili-ye/package.json
@@ -13,13 +13,16 @@
     "babel-loader": "^6.2.5",
     "babel-preset-es2015": "^6.18.0",
     "babel-preset-react": "^6.11.1",
+    "css-loader": "^0.26.1",
     "es6-promise": "^4.0.5",
     "history": "^3.0.0",
     "isomorphic-fetch": "^2.2.1",
     "react": "^15.3.1",
     "react-dom": "^15.3.1",
     "react-router": "^2.8.1",
-    "webpack": "^1.13.2"
+    "style-loader": "^0.13.1",
+    "webpack": "1.13.2",
+    "webpack-dev-server": "1.16.3"
   },
   "devDependencies": {
     "ip": "^1.1.4"
diff --git a/lili-ye/webpack.config.js b/lili-ye/webpack.config.js
index b8dfe34..59456f5 100644
--- a/lili-ye/webpack.config.js
+++ b/lili-ye/webpack.config.js
@@ -1,7 +1,7 @@
 module.exports = {
     entry: "./entry.js",
     output: {
-        path: "dist",
+        path: process.cwd() + "/dist",
         filename: "bundle.js"
     },
     module: {
@@ -17,7 +17,7 @@ module.exports = {
        },
           {
               test: /\.css$/,
-              loader: "style!css"
+              loader: "style-loader!css-loader?root."
           }
       ]
     }
```

**Comment by isliliye** [comment]
Thanks for pointing out the error. I should have tested it first. I added style and css loaders as dependencies in package.json. :)
